// app/layout.jsx
import { Inter } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Salurin",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/img/favicon.ico" },
      {
        url: "/img/favicon.svg",
        sizes: "16x16",
        type: "image/svg+xml",
      },
      {
        url: "/img/favicon.svg",
        sizes: "32x32",
        type: "image/svg+xml",
      },
    ],
    shortcut: "/img/favicon.svg",
    apple: "/img//favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/img/favicon.svg" sizes="any" />
        <link rel="icon" href="/img/favicon.svg" type="image/svg+xml" />
        <link rel="shortcut icon" href="/img/favicon.svg" />
      </head>
      <body className={inter.className}>
        {children}
        <ToastContainer autoClose={1000} />
      </body>
    </html>
  );
}
